framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%
        pools:
            app.cache.redis:
                adapter: cache.adapter.redis
                public: false
                default_lifetime: 120
            doctrine.result_cache_pool:
                adapter: app.cache.redis
            doctrine.system_cache_pool:
                adapter: app.cache.redis