lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: 'test'
    token_ttl:  86400000
    token_extractors:
        query_parameter:
            enabled: true
            name:    bearer
